server.port=8888
spring.application.name=med-config-server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.config.server.git.uri=${GIT_URI:file:///${user.dir}/med-config/src/main/resources/config-repo}
spring.cloud.config.server.git.default-label=master
